@startuml
'https://plantuml.com/state-diagram

scale 400 width
scale 400 height

state Note #aliceblue;line:blue;line.dotted;text:blue   : Blå stiplet streger indikere at man kan returnere til forsiden, via headeren på samtlige html sider.


[*] --> Forside
Forside --> Kurv
Forside --> login
Forside -->OpretKonto
Kurv --> login
Kurv -[dotted,#blue]-> Forside
login -[dotted,#blue]->Forside
OpretKonto -[dotted,#blue]->Forside

Kurv: basket.html
Forside: index.html
OpretKonto : createuser.html
login: login.html



login --> OpretKonto


state LoggedIn{
LoggedIn -[dotted,#blue]-> Forside
login --> AdminPage
login --> Customerpage
OpretKonto --> Customerpage

AdminPage : admin_page.html
Customerpage: customer_page.html



state AdminOnly{
AdminPage --> AllOrders
AdminPage --> AllOrderlines
AdminPage --> OrderDetails
AllOrders --> AdminPage
AllOrderlines-->AdminPage
OrderDetails -->AdminPage


AllOrders: all_order.html
AllOrderlines: all_orderlines.html
OrderDetails: order_details.html


}
state CustomerOnly{
Customerpage --> checkout
checkout:order_processed.html
}

}
checkout -->[*]




@enduml